import pandas as pd
import numpy as np

def generate_company_operational_data_by_product(filename='company_operational_data_by_product.csv'):
    """
    Generates a CSV file containing monthly operational data for a company's products over the past year.

    Args:
        filename (str): The name of the CSV file to be created. Defaults to 'company_operational_data_by_product.csv'.

    Returns:
        None

    The CSV file contains the following columns:
        - Date: The month and year of the data entry.
        - Product: The name of the product (e.g., Product_A, Product_B, Product_C).
        - Revenue: The revenue generated by the product in that month.
        - Expenses: The expenses incurred for the product in that month.
        - Sales_Volume: The number of units sold of the product in that month.
        - Ad_Spend: The advertising spend for the product in that month.

    Example:
        generate_company_operational_data_by_product()
    """
    # 定义时间范围
    dates = pd.date_range(start='2023-07-01', end='2024-06-30', freq='M')

    # 定义产品列表
    products = ['Personal computer', 'Laptop', 'Printer','Router']

    # 生成随机数据
    data = {
        'Date': [],
        'Product': [],
        'Revenue': [],
        'Expenses': [],
        'Sales_Volume': [],
        'Ad_Spend': []
    }

    for date in dates:
        for product in products:
            revenue = np.random.randint(10000, 50000)
            expenses = np.random.randint(5000, 30000)
            sales_volume = np.random.randint(100, 1000)
            ad_spend = np.random.randint(1000, 5000)

            data['Date'].append(date)
            data['Product'].append(product)
            data['Revenue'].append(revenue)
            data['Expenses'].append(expenses)
            data['Sales_Volume'].append(sales_volume)
            data['Ad_Spend'].append(ad_spend)

    # 创建DataFrame
    df = pd.DataFrame(data)

    # 保存为CSV文件
    df.to_csv(filename, index=False)

    print("CSV文件已生成")

# 调用函数生成CSV文件
generate_company_operational_data_by_product()